### ISSUE TITLE
Initial configuration issues (GUI Config)

### ISSUE THREAD

**Issue by frfstu** [alryaz/hass-moscow-pgu#11]
При нажатии кнопки "настроить" появляется сообщение: "Ошибка
Не удалось загрузить мастер настройки".
Данное сообщение появляется уже и в предыдущих версиях приложения(0.2.1)до которой пришлось откатиться из-за подобной же ошибки в версиях 0.2.3 и 0.2.4(в которых к тому же не передавались данные счётчиков, штрафов и задолженности).
![Screenshot_20211019-133124](https://user-images.githubusercontent.com/87616721/137894216-bb716851-f542-4fff-b70a-e166d1891f05.png)

**Comment by alryaz** [comment]
На данный момент служба ПГУ лежит (с точки зрения приложения).

@Alexunder-A-M Почему появляется проблема с "extra keys not allowed", не совсем ясно (она должна устраняться в процессе миграции обновлённой конфигурации). Требуется взглянуть на содержание `/config/.storage/core.config_entries`. Если возможно, не могли бы Вы, пожалуйста, написать мне в Telegram (@alryaz), чтобы не публиковать содержание сюда? (оно конфиденциально)

**Comment by alryaz** [comment]
@frfstu пришлите, пожалуйста, выдержу из файла `/config/.storage/core.config_entries`, заменив в ней Ваши личные данные, не удаляя какие-либо ключи.

Найти требуемую запись можно, введя в поиске по файлу `moscow_pgu`.

Пример выдержки:
```json
            {
                "entry_id": "...", /* Можно заменить содержание значения */
                "version": 3, /* Знание должно остаться оригинальным */
                "domain": "moscow_pgu",
                "title": "...", /* Можно заменить содержание значения */
                "data": {
                    "username": "...", /* Можно заменить содержание значения */
                    "password": "..." /* Можно заменить содержание значения */
                },
                "options": {},
                "pref_disable_new_entities": false,
                "pref_disable_polling": false,
                "source": "import", /* Знание должно остаться оригинальным */
                "unique_id": null,
                "disabled_by": null
            },
```

**Comment by Alexunder-A-M** [comment]
Настройки у меня через интерфейс.

**Comment by alryaz** [comment]
> Настройки у меня через интерфейс.

Внутренняя миграция.

Оказалось, что дело немного не в ней. Попробуйте сейчас обновиться на v0.2.5.
Смоделировал ситуацию, и понял, в чём крылся косяк (в собственной невнимательности).
