### ISSUE TITLE
ошибка подключения интеграции к серверу приложения 

### ISSUE THREAD

**Issue by frfstu** [alryaz/hass-moscow-pgu#18]
Не приходят данные счетчиков воды, штрафы, судебные(в один день перестало работать).
В логах пишет: aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host emp.mos.ru:443 ssl:default [Connect call failed ('212.11.155.167', 443)]
В блокировке моего файервола данный ip не числится!
Пингуется: Обмен пакетами с 212.11.155.167 по с 32 байтами данных:
Ответ от 212.11.155.167: число байт=32 время=5мс TTL=51
Ответ от 212.11.155.167: число байт=32 время=15мс TTL=51
Ответ от 212.11.155.167: число байт=32 время=8мс TTL=51
Ответ от 212.11.155.167: число байт=32 время=4мс TTL=51

Статистика Ping для 212.11.155.167:
    Пакетов: отправлено = 4, получено = 4, потеряно = 0
    (0% потерь)
Приблизительное время приема-передачи в мс:
    Минимальное = 4мсек, Максимальное = 15 мсек, Среднее = 8 мсек
Пинг по имени ip другой!
Обмен пакетами с emp.mos.ru [212.11.155.166] с 32 байтами данных:
Ответ от 212.11.155.166: число байт=32 время=5мс TTL=51
Ответ от 212.11.155.166: число байт=32 время=23мс TTL=51
Ответ от 212.11.155.166: число байт=32 время=4мс TTL=51
Ответ от 212.11.155.166: число байт=32 время=3мс TTL=51

Статистика Ping для 212.11.155.166:
    Пакетов: отправлено = 4, получено = 4, потеряно = 0
    (0% потерь)
Приблизительное время приема-передачи в мс:
    Минимальное = 3мсек, Максимальное = 23 мсек, Среднее = 8 мсек

При трассировке 212.11.155.167 выводит дубль
  9     *        *        *     Превышен интервал ожидания для запроса.
 10     6 ms     4 ms     8 ms  212.11.155.167
 11     3 ms     3 ms     7 ms  212.11.155.167

При трассировке emp.mos.ru выводит дубль
 9     *        *        *     Превышен интервал ожидания для запроса.
 10     3 ms     3 ms     3 ms  212.11.155.166
 11     6 ms     5 ms     3 ms  212.11.155.166

Итог сервер работает, но подключиться к нему интеграция не может! На Досю не похоже, вроде сервис живой хоть и с потерями при передаче пакетов. Предположение: ошибка DHCP/DNS или руки-ноги чьи-то залезли туда, куда не следует.
Исправляйте срочно!

**Comment by alexanderznamensky** [comment]
Да. где-то неделю назад перестало работать.
Очень жаль..... полезная интеграция.

UPD 13/03/2022 (HA 2022.3.3): Тоже заработало! НО: один аккаунт работает на одном сервере, а на другом сервере не работает (при одинаковых настройках). Второй аккаунт не работает ни на одном сервере...... не могу разобраться, в чем дело..... При этом другая, кмк мне кажется, похожая, интеграция Александра (Личный кабинет Интер РАО (Энергосбыт) работает на двух моих серверах с двумя аккаунтами.

**Comment by DieMetRik** [comment]
Подтверждаю. Не работает. Нужная интеграция

**Comment by Spirituss** [comment]
@alryaz Перестала работать интеграция - ошибки в логе аналогичные тем, что выше.

**Comment by neooffline** [comment]
Печально, но так же не работает...
UPD: на 06.03.2022 заработало

**Comment by pervolianinen** [comment]
> Печально, но так же не работает... UPD: на 06.03.2022 заработало



> Да. где-то неделю назад перестало работать. Очень жаль..... полезная интеграция.
> 
> UPD 13/03/2022 (HA 2022.3.3): Тоже заработало! НО: один аккаунт работает на одном сервере, а на другом сервере не работает (при одинаковых настройках). Второй аккаунт не работает ни на одном сервере...... не могу разобраться, в чем дело..... При этом другая, кмк мне кажется, похожая, интеграция Александра (Личный кабинет Интер РАО (Энергосбыт) работает на двух моих серверах с двумя аккаунтами.

Не работает. Не вводите в заблуждение. У Вас просто регистрация уже была и капчу не требует. После захода с нового устройства или для нового аккаунта, то тоже войти не сможете.

**Comment by alexanderznamensky** [comment]
@pervolianinen Да я вроде не ввожу никого в заблуждение)) Просто делился своим кейсом и не понимал, почему где-то работает, а где-то нет. Спасибо, что подсказали, в чем дело.
А в какой момент требуется капча? На сайте (при входе через браузер) вроде нет такого запроса.

**Comment by pervolianinen** [comment]
> @pervolianinen Да я вроде не ввожу никого в заблуждение)) Просто делился своим кейсом и не понимал, почему где-то работает, а где-то нет. Спасибо, что подсказали, в чем дело. А в какой момент требуется капча? На сайте (при входе через браузер) вроде нет такого запроса.

Если куки почистите то потребует капчу, а так даже логин не требуется...
Или при входе с нового устройства.
Сразу после ввода логина и пароля.

**Comment by frfstu** [comment]
Продолжаются периодические "исчезновения" (иногда по несколько раз в день!) передачи показаний холодной и горячей воды, суммы платежа ЕПД, судебной задолженности. Но если вы обратите внимание на 25ю страницу [этого](https://www.pangulab.cn/files/The_Bvp47_a_top-tier_backdoor_of_us_nsa_equation_group.en.pdf) документа, то вполне возможно (при принятии определённого характера мерах) причина разрывов связи и прочих программно-аппаратных бед ваших (mos.ru) серверов, будет устранена.

**Comment by pervolianinen** [comment]
> Продолжаются периодические "исчезновения" (иногда по несколько раз в день!) передачи показаний холодной и горячей воды, суммы платежа ЕПД, судебной задолженности. Но если вы обратите внимание на 25ю страницу [этого](https://www.pangulab.cn/files/The_Bvp47_a_top-tier_backdoor_of_us_nsa_equation_group.en.pdf) документа, то вполне возможно (при принятии определённого характера мерах) причина разрывов связи и прочих программно-аппаратных бед ваших (mos.ru) серверов, будет устранена.
Не открывайте ссылку! Вирусный контент!
Текст не ничего смысловой нагрузки и не имеет отношения к проблемам интеграции.

**Comment by frfstu** [comment]
[pervolianinen](https://github.com/pervolianinen) сам ты вирусный! то что половина серваков mos.ru хакнуто и под контролем в любое время находится, боишься что люди об этом узнают?! Объясни мне почему исчезает(прекращается) передача показаний, возникают проблемы в личном кабинете на сайте mos.ru?! Про DDoS атаки с ip адресов 194.8.70.X-194.8.71.X (вместо X любую цифру от 1 до 254 на выбор)  и 95.173.144.X - 95.173.159.X (принцип тот же!) мне расскажи!

**Comment by pervolianinen** [comment]
> [pervolianinen](https://github.com/pervolianinen) сам ты вирусный! то что половина серваков mos.ru хакнуто и под контролем в любое время находится, боишься что люди об этом узнают?! Объясни мне почему исчезает(прекращается) передача показаний, возникают проблемы в личном кабинете на сайте mos.ru?! Про DDoS атаки с ip адресов 194.8.70.X-194.8.71.X (вместо X любую цифру от 1 до 254 на выбор) и 95.173.144.X - 95.173.159.X (принцип тот же!) мне расскажи!

У пользователей НАШЕГО сервиса mos.ru никаких проблем нет. Про какой сервис говорите Вы (который не ваш), я не знаю.
В данной теме обсуждается интеграция, автор который в данный момент не может внести корректировки в код реализующий авторизацию. 
В связи с полным отсутствием в коде каких либо комментариев, исправить достаточно проблематично.

**Comment by frfstu** [comment]
> > [pervolianinen](https://github.com/pervolianinen) сам ты вирусный! то что половина серваков mos.ru хакнуто и под контролем в любое время находится, боишься что люди об этом узнают?! Объясни мне почему исчезает(прекращается) передача показаний, возникают проблемы в личном кабинете на сайте mos.ru?! Про DDoS атаки с ip адресов 194.8.70.X-194.8.71.X (вместо X любую цифру от 1 до 254 на выбор) и 95.173.144.X - 95.173.159.X (принцип тот же!) мне расскажи!
> 
> У пользователей НАШЕГО сервиса mos.ru никаких проблем нет. Про какой сервис говорите Вы (который не ваш), я не знаю. В данной теме обсуждается интеграция, автор который в данный момент не может внести корректировки в код реализующий авторизацию. В связи с полным отсутствием в коде каких либо комментариев, исправить достаточно проблематично.
![mos ru](https://user-images.githubusercontent.com/87616721/161273724-2e30550f-3f1a-4072-bc61-407327376866.png)


Я пользователь ВАШЕГО mos.ru сервиса, и о проблемах пишу как минимум с начала 2022 года! А если в коде всё в порядке, то почему так часто все показания перестают передаваться и отображаться и сервер недоступен (даже не пингуется)?! Картинку посмотри, надеюсь дойдёт до тебя, то о чём я говорю.

**Comment by pervolianinen** [comment]
> > > [pervolianinen](https://github.com/pervolianinen) сам ты вирусный! то что половина серваков mos.ru хакнуто и под контролем в любое время находится, боишься что люди об этом узнают?! Объясни мне почему исчезает(прекращается) передача показаний, возникают проблемы в личном кабинете на сайте mos.ru?! Про DDoS атаки с ip адресов 194.8.70.X-194.8.71.X (вместо X любую цифру от 1 до 254 на выбор) и 95.173.144.X - 95.173.159.X (принцип тот же!) мне расскажи!
> > 
> > 
> > У пользователей НАШЕГО сервиса mos.ru никаких проблем нет. Про какой сервис говорите Вы (который не ваш), я не знаю. В данной теме обсуждается интеграция, автор который в данный момент не может внести корректировки в код реализующий авторизацию. В связи с полным отсутствием в коде каких либо комментариев, исправить достаточно проблематично.
> > ![mos ru](https://user-images.githubusercontent.com/87616721/161273724-2e30550f-3f1a-4072-bc61-407327376866.png)
> 
> Я пользователь ВАШЕГО mos.ru сервиса, и о проблемах пишу как минимум с начала 2022 года! А если в коде всё в порядке, то почему так часто все показания перестают передаваться и отображаться и сервер недоступен (даже не пингуется)?! Картинку посмотри, надеюсь дойдёт до тебя, то о чём я говорю.

1. Мне ваша картинка ничего не говорит. Ну кроме того, что вам нужно обратится к вашему провайдеру... Не ясно при чем тут строчки с кусками текста имени домена mos.ru (это даже не pgu.mos.ru) и при чем тут вода не ясно.
2. Mos.ru явно не мой сервис и ко мне не имеет никакого отношения. Но все на нем работает отлично.
3. Данная тема про интеграцию для ha проблема известна и пользователям и автору. При наличие старой авторизации (в бэкапа). Данная интеграция отлично работает. 
4. Вы явно никогда не пользовались pgu.mos.ru если считаете, что это одно и тоже с доменом mos.ru.

**Comment by frfstu** [comment]
У меня HA работает стабильно, хорошо настроен, но время от времени, друг за
другом перестают получать данные из внешних источников интеграции мос.ру и
мосэнергосбыт. Делая это иногда по отдельности, а иногда обе сразу! При
этом интернет работает, сервер HA и все другие запущенные на нем службы и
интеграции работают отлично, ошибок кроме как в вышеуказанных интеграциях
не возникает. Начинаю проверять, и выясняется что сервер поставляющий эти
самые данные не доступен и в сети не пингуется и роуты до него не доходят
обрываясь на шлюзах в их локальной сети. А вот теперь объясните мне
пожалуйста (потрудитесь так сказать) каким образом вышеуказанные интеграции
в течении нескольких часов одного дня могут перестать отображать данные
либо полностью, при этом предлагая удалить несуществующий более объекты,
либо не отображать часть данных из передаваемых сервером, а потом
возобновить это отображение и через 2-3 дня и через неделю (сами собой), а
в этот период при проверке сервера поставляющего эти самые данные,
оказывается что он не в сети! Вот как?! Скриншот прилагается.

пт, 1 апр. 2022 г., 16:48 pervolianinen ***@***.***>:

**Comment by pervolianinen** [comment]
1. Интеграция pgu.mos.ru в принципе не может у вас работать, она у разработчика не работает и он об этом в курсе.
2. Исходя из вашего набора строк текста я ещё раз настоятельно рекомендую обратиться к вашему провайдеру, учитывая что недоступно у вас намного больше чем поддомене mos.ru. 
3. Ресурсы находятся не в их "локальной" сети они даже в разных местах, отличных от места расположения серверов днс.

**Comment by frfstu** [comment]
У Вас по видимому не остаётся ничего кроме как выставлять меня на
посмешище! Проблема ведь есть, и Вы о ней прекрасно знаете, признать это
просто не можете или не хотите! У моего провайдера всё в порядке, у меня
соответственно всё что с ним связано тоже. Но в отличие от Вас и ваших
вышестоящих служб, я фиксируя проблемы в работе каких-либо сервисов
предпринимаю соответствующие меры по устранению проблем, решая их совместно
с владельцами этих сервисов, и нормальные люди, внимательно ознакомившись с
тем что я им написал в письме или объяснил в телефонном разговоре, в
оперативном режиме исправляют ошибки. У вас же всё всегда исправно
работает, это не работает у остальных, пусть разбираются у себя(напоминает
итог обращений в техподдержку Билайн и Акадо, там также по любым возникшим
обращениям о проблеме, отвечают). Сериал The IT Crowd посмотрите, пополните
список отговорок на обращения.

сб, 2 апр. 2022 г., 09:08 pervolianinen ***@***.***>:

**Comment by alryaz** [comment]
@frfstu авторизация сейчас не работает у меня действительно (она поменялась на ресурсе в пользу внешней через OAuth; у тех, у кого она до сих пор работает, используются старые ключи сессии).

**По поводу ошибки из Вашего первого сообщения:** причиной данной ошибки компонент являться не может, т.к. используются те же самые зависимости и модули, которые используются Home Assistant. Компонент не выполнен инвазивным образом.

В логах указана ошибка соединения с :443 (коим является SSL). Пингом эта ошибка не диагностируется, разве что на самой первой стадии (т.к. пинг использует протокол ICMP, не TCP). Попробуйте выполнить команду `openssl s_client -connect emp.mos.ru:443` в терминале Linux, действующем на узле, не являющимся Вашим Home Assistant, но находящимся в той же сети.

Если команда завершится с ошибкой, тогда одно из следующего:
- неким образом производится инвазивный DPI, который портит сертификат SSL;
- правила брандмауэра L3+ портят сигнатуру пакетов (хотя в данном случае они бы отбрасывались на уровне ядра);
- NAT маршрутизатора работает некорректно;
- не обновлены CA-сертификаты на узле с Home Assistant.

Если команда завершится успешно, тогда проверьте в первую очередь CA-сертификаты в Home Assistant.

**EDIT:** Полезным будет также увидеть вывод `iptables -L -v -n` и `iptables -t nat -L -v -n` как на Home Assistant, так и, если это возможно, на маршрутизаторе.

**Comment by frfstu** [comment]
![Screenshot](https://user-images.githubusercontent.com/87616721/161377754-959e1a88-065b-4b4a-bfdf-6acfb12c2800.png)

**Comment by frfstu** [comment]
![Uploading Screenshot-1.png…]()

**Comment by frfstu** [comment]
![Screenshot-1](https://user-images.githubusercontent.com/87616721/161378113-20eafdf7-0366-4da2-9d84-fe01807fdae8.png)

**Comment by alryaz** [comment]
Действительно, проблема с CA-сертификатами. Проверьте, есть ли у Вас в системе упомянутый в ошибке (5 строка терминала сверху) сертификат (в `/etc/ssl/certs`).

Как, по-хорошему, должна проходить верификация:
```sh
# openssl s_client -showcerts -connect emp.mos.ru:443 </dev/null | head -6
depth=2 C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust RSA Certification Authority
verify return:1
depth=1 C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Organization Validation Secure Server CA
verify return:1
depth=0 C = RU, ST = Moskva, O = Department of Information Technology in Moscow, CN = *.mos.ru
verify return:1
CONNECTED(00000003)
---
Certificate chain
 0 s:C = RU, ST = Moskva, O = Department of Information Technology in Moscow, CN = *.mos.ru
   i:C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Organization Validation Secure Server CA
-----BEGIN CERTIFICATE-----
DONE
```

И, соответственно, актуальный отпечаток сертификата из Ubuntu 20.04:
```sh
# openssl x509 -in /etc/ssl/certs/USERTrust_RSA_Certification_Authority.pem -text | head -11
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            01:fd:6d:30:fc:a3:ca:51:a8:1b:bc:64:0e:35:03:2d
        Signature Algorithm: sha384WithRSAEncryption
        Issuer: C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust RSA Certification Authority
        Validity
            Not Before: Feb  1 00:00:00 2010 GMT
            Not After : Jan 18 23:59:59 2038 GMT
        Subject: C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust RSA Certification Authority
```

**Comment by alryaz** [comment]
Дополнительно можно проверить, использует ли вообще OpenSSL корневые сертификаты местные; однако, к сожалению, это уже далеко не уровень обсуждения компонента.

Если Home Assistant у Вас на аналогичной системе, проверьте то же самое и на нём. Вероятнее всего у Вас отсутствуют актуальные сертификаты удостоверяющих центров, или же OpenSSL (или Python) не настроен на использование этих сертификатов (зачастую последний использует свои собственные сертификаты, не системные).

**Comment by frfstu** [comment]
Всё не прогружает информацию, сервер недоступен (no answer from emp.mos.ru). Нет, на Солярисе я HA ещё не заводил.

**Comment by frfstu** [comment]
Нет у меня ни сертификатов ни s_client'а на сервере с НА

**Comment by frfstu** [comment]
Мое мнение по поводу использования "непонятного свойства" удостоверяющих центров сертификации иностранных государств для работы в государственных информационных системах, это ни что иное как подрыв безопасности страны! А весь этот "мудрёж" с сертификатами и при имеющейся (действующей) авторизации по логину и паролю (при условии что все ключевые узлы вашей сети имеют свои внутренние сертификаты проверки между собой) для обычных людей, ни что иное как очередная строка избыточных расходов бюджета и очередная сертификатокуаркодная мания. Проще удалить вашу интеграцию и жить спокойно дальше, чем идти на уступки ваших "хотелок" и "плодить" у себя кучу всего ненужного и потенциально уязвимого, особенно при условии постоянно расширяющегося списка санкций в отношении страны и ее граждан.
