### ISSUE TITLE
События, как результат передачи значений счетчиков в ха

### ISSUE THREAD

**Issue by Spirituss** [alryaz/hass-moscow-pgu#2]
Сейчас очень не хватает генерации событий в ха по итогам передачи значений счетчиков. 
Пример такой реализации есть здесь: https://github.com/kkuryshev/ha_mosportal.

**Comment by alryaz** [comment]
События имеются, но исчезли из документации.

Ожидайте v0.2.0.

**Comment by alryaz** [comment]
README.md содержит указания по службе + события
