### ISSUE TITLE
Неправильная ссылка на скриншот в README.md

### ISSUE THREAD

**Issue by chex01** [alryaz/hass-moscow-pgu#6]
В README.md нужно заменить: 
`  <img src="https://raw.githubusercontent.com/alryaz/hass-moscow-pgu/main/images/push_indication_service.png" alt="Школьный дневник">`

 на:
`  <img src="https://raw.githubusercontent.com/alryaz/hass-moscow-pgu/main/images/diary.png" alt="Школьный дневник">`

**Comment by NikitaKorneev** [comment]
#8
