### ISSUE TITLE
desciption вместо descRiption

### ISSUE THREAD

**Issue by NikitaKorneev** [alryaz/hass-moscow-pgu#7]
Не уверен - с чьей стороны возникает эта ошибка, с серверов ФССП так приходит, или из-за этой интеграции, но если есть задолженность у ФССП- то один из атрибутов долга содержит орфографическую ошибку...

<img width="611" alt="Screenshot 2021-10-01 at 14 49 10" src="https://user-images.githubusercontent.com/60179299/135615677-61f6d0e0-dd55-4d86-85a8-fc1ff4868bdd.png">

**Comment by alryaz** [comment]
Исправлено, спасибо!

v0.2.2 будет содержать данное исправление.

**Comment by NikitaKorneev** [comment]
Блин, придётся все автоматизации переписывать:):):):)
